### ISSUE TITLE
Re-order ability

### ISSUE THREAD

**Issue by AlfaOmega33** [SecUSo/privacy-friendly-weather#10]
Hi! Please, add an ability, in the settings, to re-order the saved locations by date or by name!

**Comment by Yonjuni** [comment]
Thanks for the comment.
It is possible to reorder the locations by drag and drop. 

Automatic sorting could be integrated in future updates. We will discuss in our group.

**Comment by Yonjuni** [comment]
Closed #10 because behaviour will change with the redesign
