### ISSUE TITLE
Move to Openweather One Call API

### ISSUE THREAD

**Issue by woheller69** [SecUSo/privacy-friendly-weather#108]
One Call API (https://openweathermap.org/api/one-call-api) provides all information in one API call and can also be used with free subscription. The number of calls is reduced by 2 because it is not necessary to read current weather and then forecast. All in one call.

This One Call API provides the following weather data for any geographical coordinates:

    Current weather
    Minute forecast for 1 hour  (only for some areas, can be skipped in the request, not needed in my view)
    Hourly forecast for 48 hours (would also provide rain volume)
    Daily forecast for 7 days  (temperatures for morning, day, evening, night and min/max, daily weather ID, Midday UV index etc.)

Some of the other open issues could be more easily addressed.

The call requires LAT / LON instead of cityID. I don´t think we have that at the moment.

Some matching parameters in JSON data are different.
https://openweathermap.org/darksky-openweather#match

The hourly forecast for 48h could be shown in the course of day panel where it is already possible to scroll through the data.

What do you think?

**Comment by sleep-yearning** [comment]
This sounds like a great improvement. We will keep this open and in mind but it's not priority yet.

**Comment by woheller69** [comment]
I would propose several steps:
1. Add Lat/Lon to cities, so that it can be used in an API call. Don't know, how to do this. I am new to Java...

2. keep current weather as it is on old API and use one call API with Lat/Lon for forecasts. That keeps changes much simpler but with a few changes in JSON data extraction gives access to the new features. 

3. maybe sometime also change current weather and with that reduce number of API calls.

**Comment by woheller69** [comment]
So far I have changed current weather and week forecast. They are fetched from one call API.
In course of day I also like the 3h forecast for 4 or 5 days. Others max like a more detailed hourly forecast for 48h.
I think this should be selectable in settings, like the preferences for widgets.

**Comment by sleep-yearning** [comment]
This can be close, right?

**Comment by woheller69** [comment]
yes
