### ISSUE TITLE
Stuck at boot screen

### ISSUE THREAD

**Issue by Primokorn** [SecUSo/privacy-friendly-weather#11]
Hi,
I've just installed your app from F-Droid on my Nexus 5 - Android 6.0.1 and I'm stuck at the first screen. ([Screenshot](https://osine.cozycloud.cc/apps/photos/photos/cc9029c7ccb261e669cff3e3c7143d90.jpg))

**Comment by Yonjuni** [comment]
Thanks for the comment. I unfortunately cannot open the screenshot, could you please submit it to us in a different way? Or could describe what you meant by "first screen"?

**Comment by Primokorn** [comment]
Sorry. [Here you go](https://osine.cozycloud.cc/public/photos/#albums/cc9029c7ccb261e669cff3e3c71434e9).

**Comment by Yonjuni** [comment]
Thanks, the boot at the first start usually takes quite some time to set up the application. 
I also use a Nexus 5 with Android 6.0.1 in my case it could take up to 20 seconds. 
But we will investigate this problem further.

**Comment by Primokorn** [comment]
Gotcha. When I saw the system popup 'Do you want to close Weather?' I tough it was stuck.
Abnormally long to reach the main screen, though.
Thanks.

**Comment by Yonjuni** [comment]
Okay, but it finally worked?

**Comment by Primokorn** [comment]
Yep.
