### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by MichaelMcDonnell** [SecUSo/privacy-friendly-weather#116]
It would be nice to have a dark theme in addition to the current light theme. A system dark theme was added to Android 10 [1]. A lot of apps implement a dark theme that is independent of the Android version and system settings.

I use dark theme on my apps to avoid bright lights at night which disturb the circadian rhythm. Dark themes can additionally lower power usage on phones with OLED screens.

[1] https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by sleep-yearning** [comment]
This is something we want to work on in the future

**Comment by hurzl** [comment]
The light theme could be improved, too. It's almost impossible to recognize the small icons on this blue background,  especially rain and snow.

**Comment by sleep-yearning** [comment]
Do you mean rain and snow are hard to distinguish from each other? On the devices I test, it is not too small/hard to see. Please elaborate

**Comment by hurzl** [comment]
It's grey on blue, almost the same brightness, little dots or drops, very hard to distinguish. The smaller the harder.

**Comment by sleep-yearning** [comment]
The weather icons were made more easily distinguishable recently. A dark theme was also implemented.
Closing this issue.
