### ISSUE TITLE
Current weather icon

### ISSUE THREAD

**Issue by MichaelMcDonnell** [SecUSo/privacy-friendly-weather#117]
The icon that shows the current weather (not sure what it is called) is showing the wrong icon. It is showing the night icon but should be showing a sun (it is mid-day here in California).

I think the problem is related to issue #93 and issue #96 where the wrong time was used. That would make sense because I'm in California and the app is developed in Europe. The time difference is 9 hours between Pacific standard time (PST) and central European time (CET). That means it is night in Europe.

I'm running master from August 8 2020 (commit 40668b4bdd0208f76f98bb7e0be3b0b1acf3dfd0). It used to work so I think the recent fixes for #93 and #96 broke it.

**Comment by MichaelMcDonnell** [comment]
![Screenshot_20200812-113750](https://user-images.githubusercontent.com/20253/90056171-4b4f1a80-dc93-11ea-8839-010343772416.png)

**Comment by MichaelMcDonnell** [comment]
Hi @sleep-yearning I think the recent fixes for #93 and #96 broke the current weather icon.

**Comment by woheller69** [comment]
I rather think it is a Mountain View issue. I just set my time zone to Los Angeles.  (2pm LA time)
And with Mountain View I see the same problem. But there are several Mountain Views, e.g. Mountain View 66558 (US). There it shows day, also for Los Angeles the icon is correct.

**Comment by MichaelMcDonnell** [comment]
Now Mountain View (California 94040) is showing correctly too. I'll keep an eye on it.

**Comment by MichaelMcDonnell** [comment]
I got the same issue again today. It is 11:15 and it is showing night time icons for both Mountain View and Los Angeles. It seems to be time dependent. I'll check again after noon to see if it switches to day icon just like yesterday.

**Comment by woheller69** [comment]
I see a problem here as well in the morning, when I should be sleeping. Day icon before sunrise. Will think about it next week. Maybe a problem of the timestamp which I think is not taken from API response or some modulo 24h stuff with sunset/sunrise?

**Comment by woheller69** [comment]
I now think the addition of TimeZoneSeconds stuff in comparison with sunrise/sunset is wrong here.
Will try next week, when I am back home.


if(currentWeatherDataList.getTimestamp()+currentWeatherDataList.getTimeZoneSeconds() >currentWeatherDataList.getTimeSunrise() && currentWeatherDataList.getTimestamp()+currentWeatherDataList.getTimeZoneSeconds() < currentWeatherDataList.getTimeSunset()){
            isDay = true;

**Comment by MichaelMcDonnell** [comment]
The current temperature is also broken in the latest build btw.

**Comment by MichaelMcDonnell** [comment]
I would recommend extracting some of this code into separate functions and writing some simple unit tests. Unit tests make it much easier to ensure timezones and edge cases are handled correctly.

**Comment by sleep-yearning** [comment]
Unit tests will hopefully come soon, but as I see it @woheller69 resolved this issue for now. Feel free to reopen if the problem persists.

**Comment by MichaelMcDonnell** [comment]
Thank you! The current weather icon is correct now! :-)

Unfortunately the Course of the Day icons seem to have regressed. It is showing all moons now (see issue #131). I do not know if that regression is related but I would not be surprised. I was surprised by how the data was processed when I read the code.

**Comment by MichaelMcDonnell** [comment]
I did a bisect and the all moons issue was introduced by a later commit 869183946ccfb500075f71a51a82bdd910502783.
