### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by MichaelMcDonnell** [SecUSo/privacy-friendly-weather#118]
I noticed there are no unit tests (beside the ExampleUnitTest). Unit tests are important to ensure that regressions are not introduced. I noticed a regression in issue #117 which might have been avoided by having unit tests.

The unit tests should preferably be run by a CI system before new code is pulled. My pull request #114 runs the gradle test target.

The first step is to identify which parts of the code to unit test. It seems like the code that transforms the raw data into the displayed data is a good candidate for unit testing.

**Comment by Kamuno** [comment]
Thanks for the suggestion. We added some tests and will continue to add tests. I will close this issue for now. Thank you for your help with the CI.
