### ISSUE TITLE
no autorotation, letters on right side 'cutted', when searching a location no scrolling possible.

### ISSUE THREAD

**Issue by paulle** [SecUSo/privacy-friendly-weather#12]
Thank you for this beautiful app.
But I found some minor issues, autorotation is not possible. Last letters on right side get 'cutted'. When searching a location, I cannot scroll through the results, I can only choose from the visible ones.

**Comment by paulle** [comment]
![screenshot_20161110-141905](https://cloud.githubusercontent.com/assets/4852079/20178453/7f4aec86-a751-11e6-865b-957b27e9adec.png)
not scrollable

**Comment by paulle** [comment]
![screenshot_20161110-143052](https://cloud.githubusercontent.com/assets/4852079/20178682/90acc340-a752-11e6-8286-ba8e028a2f77.png)
text cutted

**Comment by Yonjuni** [comment]
Thanks for the comment, we will check these problems and solve them with our next update.
Could you tell us the device that you are using?

**Comment by paulle** [comment]
Yes I'm using a xperia xz (Sony), it has a 5,2 display with a 1080x1920 pixels resolution.

Am 10. November 2016 16:19:49 MEZ, schrieb Karola Marky <notifications@github.com>:
>Thanks for the comment, we will check these problems and solve them
>with our next update.
>Could you tell us the device that you are using?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SecUSo/privacy-friendly-weather/issues/12#issuecomment-259716998

-- 
K-9 Mail

**Comment by Yonjuni** [comment]
Solved the scrolling problem with commit 98d07b09b1bc29a764e0c5b4eeccbaee85db5f66

**Comment by Yonjuni** [comment]
Scrolling problem on details view solved with commit 9aec28c07790090170f3e88ef5bbbb67cbc098e4

**Comment by Yonjuni** [comment]
Regarding the scrolling from left to right. I assume that the font size of your device differs from the usual 100% 
I will put this problem in our issue list, but unfortunately we cannot save this problem in the next version.

**Comment by Yonjuni** [comment]
Closed #12
Remaining issues added to https://github.com/SecUSo/privacy-friendly-weather/issues/13

**Comment by paulle** [comment]
Yes you are right, the font size of my device differs from the usual 100% . Font size is set big (groß), because it's easier to read for me (bad eyes).
