### ISSUE TITLE
Add rain volume to course of day adapter

### ISSUE THREAD

**Issue by woheller69** [SecUSo/privacy-friendly-weather#122]
Does anybody really need relative humidity in 3h intervals? I would prefer to have rain volume there or as an additional line.

**Comment by woheller69** [comment]
Shows rain and snow volume as an additional line in course of day for next 72h. 
(I could even find a city, where it is snowing now for testing : Grytviken)
Hope you like it.

![rainvolume](https://user-images.githubusercontent.com/68678880/90606381-0af61c00-e200-11ea-8689-8e94c0f1130d.png)

![snow](https://user-images.githubusercontent.com/68678880/90606741-85bf3700-e200-11ea-9c3d-e6c94f1f95dd.png)

**Comment by sleep-yearning** [comment]
Thx!
