### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by franklinbill** [SecUSo/privacy-friendly-weather#126]
Dear developer
In the process of using, I found a bug in layout / display. As shown in the figure, At the top of the search page, the upper part of the text "around a location" is blocked.
App version is 1.2, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/91206074-1fbf3c00-e739-11ea-9140-a569a4da2074.png)

**Comment by sleep-yearning** [comment]
Thank you for the feedback, we will have to look into this.
