### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [SecUSo/privacy-friendly-weather#128]
Hi there,

I'm founding this error in the app beginning:

![WhatsApp Image 2020-08-25 at 08 17 12](https://user-images.githubusercontent.com/12240167/91208998-726d0980-e6e1-11ea-925c-72c57bcf5c1f.jpeg)

App version 2.2

There is no button bellow to add the place.

Phone is Redmi 8A

Many thanks

**Comment by sleep-yearning** [comment]
Hello @ViniciusBRodrigues, the OK Button should work as soon as you type and select a city in the editable text field.
Let me know if this solves the issue or there is something else.

**Comment by ViniciusBRodrigues** [comment]
Hi, there is no field to select a city :(

**Comment by sleep-yearning** [comment]
If you click above the line, there should appear the option to input text.

**Comment by ViniciusBRodrigues** [comment]
Hmm I see! It was hard to figure out it. Many thanks!
