### ISSUE TITLE
Default Location not working

### ISSUE THREAD

**Issue by woheller69** [SecUSo/privacy-friendly-weather#129]
With long press I select one of my cities. It is then marked with a star.
When I go back to weather data the first city on my list is shown.
Same when I close and start the app.
So I guess setting a default location has no effect...
Or what is the expected behaviour?
I am running Android 10 (LineageOS).

Also current weather data is not updated when I open the app. Even when I press the update button.
Only when I rotate the display or close and open the app the latest data is shown.

**Comment by sleep-yearning** [comment]
Default location will be removed when city sorting is implemented. I am aware of the update problem.
