### ISSUE TITLE
Postal Code and other changes in latest version (commit cbcbb7c2c50be38b69791295e2c462750a5c5fb2)

### ISSUE THREAD

**Issue by woheller69** [SecUSo/privacy-friendly-weather#132]
I saw postal code was removed in one of the latest commits. I don´t think we should do that. Otherwise it will be difficult to distinguish between cities with same name. And who knows lat/lon for his city...
I think we should keep it in addition to lat/lon. Otherwise we would need to show the selected city on a map like Forecastie does.

Do we really need min/max of relative humidity for every day of the week? 
I could imagine more important data to be displayed on the rare space available.
E.g. total precipitation for the day or UV index (once we use one call API).

Another difference I see is that now the 5 day forecast shows today + 4 days where in earlier versions the week forecast started with tomorrow. So one day is missing now...

**Comment by sleep-yearning** [comment]
Well, I know it's easier to recognize postal code than coordinates obviously. The problem here is just that the dataset doesn't include them anymore. Meaning the new source of the city list has no field for it and the previous was very incomplete. I figured to get rid of an inconsistent feature.

As for the ability to distinguish: the plan is to later show a map view when new cities get added so it becomes even more intuitive. So jeah, what you mentioned. 

For the humidity: I plan on making it an option in the settings much like for the widgets. With precipitation probably becoming default then.

I'll have to check how far the Forecast data goes, but showing one more day should be possible in principle, when it happened before.

**Comment by woheller69** [comment]
Some more problems I see with latest version:
It is now 15:14. When I press "refresh" the first forecast shown is for 17:00 which is correct. When I close the app and open it again it shows the old forecast for 14:00 in the first place, which should no longer be used. When I switch between cities it sometimes shows 14:00 and sometimes 17:00. Quite strange...

I would expect current temperature to update immediately when I press "refresh". But it does not, and the value shown is not the same as I  get when entering the API call (http://api.openweathermap.org/data/2.5/weather?id=...) directly into my browser.
E.g. the app gives me 19.6°C, the API returns main:temp:293.86K which is 20.71°C.

**Comment by woheller69** [comment]
Opened the app in the morning. It started very slow... Then it showed 08:00 as first forecast. After switching between several cities it shows 05:00 as first forecast.

**Comment by woheller69** [comment]
![Screenshot_20200910-142937_Wetter](https://user-images.githubusercontent.com/68678880/92730377-f5de5a00-f373-11ea-877c-49d3dd94568d.png)
![Screenshot_20200910-142951_Wetter](https://user-images.githubusercontent.com/68678880/92730425-0c84b100-f374-11ea-95d7-397ac8892eb8.png)

Also the values are changing. I open the app and it shows forecasts starting 17:00. T at 17:00 will be 22.2°C.
See first image. This value is the same when I use an older app version.
Then I click between three cities and go back to the first.
Now forecasts start at 14:00 but T at 17:00 changed to 21.1°C.
See second image.
After pressing refresh values are correct again and start at 17:00.

**Comment by woheller69** [comment]
Now, 3h later it still shows the same data for 17:00, 20:00, 23:00 after swichting beween cities. So somewhere old data is stored and not being deleted/replaced...

**Comment by woheller69** [comment]
Maybe you want to try the changes in my newmaster branch. For me everything works great now

**Comment by sleep-yearning** [comment]
I believe the various issues discussed here are solved by now. Feel free to reopen if not. The referenced PR is incorporated as well, even if not through GitHub directly.
