### ISSUE TITLE
Wrong icon in week weather

### ISSUE THREAD

**Issue by woheller69** [SecUSo/privacy-friendly-weather#135]
The screenshot shows forecast data for Thursday. Cloudy all the day. Except during night at 2:00 (which is not an this picture)
So the icon for Thursday should be something without sun...

![Screenshot_20200923-064111_Wetter](https://user-images.githubusercontent.com/68678880/93969131-72593b80-fd6b-11ea-97fe-f24012bb4893.png)

**Comment by woheller69** [comment]
PS: Old released version from F-Droid showes correct icon. So probably one of the newer commits causes the error

**Comment by woheller69** [comment]
Best solution will be to read week weather from one call API. There the most prevalent weather for the following 7 days is provided including temperatures for morning, day, evening, max, min, etc. No further processing needed.
So we should probably not waste time here and move to one call API asap...

**Comment by sleep-yearning** [comment]
This should be fixed by now, we are using the OneCallAPI.
