### ISSUE TITLE
idea for improvement

### ISSUE THREAD

**Issue by jobbb** [SecUSo/privacy-friendly-weather#14]
Hi, thank you for this app!!
Please can you make 2 improvements?
I added a city.  I see only the weather from today.
If i click on this city i see the detail-weather from today, but for the next day i must choose a weekday to look for the weather. For the next day i must choose a weekday etc.
1. Please can you display the weather from today and the next 5 days in one screen. Or if you want to make a option where i choose the number of days i want to see.
For example like the app WeatherPro Free: I see the weather for all the next days for one city, I can choose each day for details. At the top there is the name of the actual city, if i click on the city at the top i can choose other cities to display the weather (before i must add my favorite cities).
2. Please can you add a widget to see the weather from today and the next 5 days.

Best regards

**Comment by Yonjuni** [comment]
Thanks for submitting your ideas. 
We are already planning to add a widget in one of the next versions. You can follow the development of the widget here: https://github.com/SecUSo/privacy-friendly-weather/issues/18
During the planning phase for this app we have discussed different possibilities to display the forecast. The current solution seemed the best for us. Thus, we unfortunately do not plan to change it soon.
