### ISSUE TITLE
Updated Weather Data for cities glitches back to previous values when changing tabs.

### ISSUE THREAD

**Issue by sleep-yearning** [SecUSo/privacy-friendly-weather#142]
When an update is requested, the city view reflects those new values. When switching between other cities for a bit, the values for the updated city reset somehow.

**Comment by woheller69** [comment]
Maybe that is the same as I described in #132  (my 2nd post)?
That should be gone if you merge my pull request. I don't have any issues. 
The only thing I never tested is Widgets.

**Comment by sleep-yearning** [comment]
should be fixed by 5b4a685a
