### ISSUE TITLE
Problem deleting city

### ISSUE THREAD

**Issue by woheller69** [SecUSo/privacy-friendly-weather#143]
Add new city
Immediately delete this city before switching activity
Then switch to forecast activity

The deleted city will still be there...
Ideas?

**Comment by sleep-yearning** [comment]
The reason seems to be the asynchronous database call to add the city has not been finished. So basically the city gets deleted before its added.

**Comment by woheller69** [comment]
I already fixed it in my app. 

https://github.com/woheller69/weather/commit/6870a4b3309b899481b06241c8d21164cc3cf47d

**Comment by sleep-yearning** [comment]
cool thanks!
