### ISSUE TITLE
Weather radar maps please

### ISSUE THREAD

**Issue by DGMurdockIII** [SecUSo/privacy-friendly-weather#15]
I would like to see Weather Radar maps  be added to this app

**Comment by Yonjuni** [comment]
Thanks for this idea. We will discuss this. As it is a big feature it cannot not be implemented soon. 
We will use this issue to keep you informed. 
A possible way to add weather maps would be by using OpenWeatherMap (https://openweathermap.org/weathermap) the free package includes pas usage as well.

**Comment by woheller69** [comment]
What about using Rainviewer API? Here is an example for an animated map with rain radar:
https://github.com/rainviewer/rainviewer-api-example/blob/master/rainviewer-api-example.html

Needs to create a MapActivity and pass latitude, longitude, zoom, and API key to this html.

**Comment by petermayer** [comment]
This is available since version 2.4: https://github.com/SecUSo/privacy-friendly-weather/releases/tag/v2.4
