### ISSUE TITLE
Add Probability of Rain

### ISSUE THREAD

**Issue by kojid0** [SecUSo/privacy-friendly-weather#153]
Openweathermaps shows a probability of rain for each of the next 8 days (and hourly). It would be cool if this was implemented.

![icon](https://user-images.githubusercontent.com/24477557/112386810-b533a600-8cf1-11eb-998b-6b4e6e3da57b.png)

**Comment by sleep-yearning** [comment]
I checked the API, the hourly/daily.pop responses hold this information. This means the data should be there.

**Comment by sleep-yearning** [comment]
This is incorporated since b2e13041b4beda20eed78309a33f43726e404826. Closing now. It's missing as a widget option though.
