### ISSUE TITLE
Error while updating forecast, please try again!OpenAPI1 - when using newly created unique API key

### ISSUE THREAD

**Issue by cidetraq** [SecUSo/privacy-friendly-weather#155]
I went to OpenWeather and created an account, and pasted the default API key that was generated into Privacy Friendly Weather for Android v2.4.2 . Using the default, shared key in the app works just fine but using my own unique one does not.

**Comment by sleep-yearning** [comment]
Did the problem persist? The keys can take a while to get activated.

**Comment by cidetraq** [comment]
yeah I retried with the same API key today and it worked, must have been like you said
