### ISSUE TITLE
Weather radio support 

### ISSUE THREAD

**Issue by DGMurdockIII** [SecUSo/privacy-friendly-weather#16]
I would like to see Weather radio support be added to this app    https://www.wunderground.com/wxradio/

**Comment by Yonjuni** [comment]
Could you describe your intended feature in more detail?

**Comment by DGMurdockIII** [comment]
The ability to be able to listen to my local weather radio station in the app would be very helpful

**Comment by Yonjuni** [comment]
Thanks for the description. Unfortunately, this is not a feature we are planning to add in further versions as we wish to keep the app quite simple.

**Comment by zubgjacc** [comment]
Terrestrial broadcast is the most private of all.
Could you implement from this open source app?

https://github.com/kconger/org.thecongers.sdrweather
