### ISSUE TITLE
Horizontal scroll to navigate between days

### ISSUE THREAD

**Issue by sciamano** [SecUSo/privacy-friendly-weather#20]
currently to navigate between the days on the overview screen, I have to press the day text, like "Mo." "Tu" and that requires some precission as the screen area for that is sort of small. Much easier will be to just swipe the screen to the left or to the right to scroll from "Mo." to "Tu"  etc. The same idea applies ot the "course of the day" as well.

**Comment by subiol** [comment]
+1

It would be much easier and productive if course of the day could be seen by just swiping down.

**Comment by logos88** [comment]
I agree with sciamano and subiol. 

I think it would be nice that if you swiped to the right yo had a picture similar to this:

![eltiempo1](https://cloud.githubusercontent.com/assets/4170088/20340121/56c55fba-abe0-11e6-9f3f-b96379a9a1da.jpg)


This way, you could go to a specific day picking that day from the main scree, or you could have a general picture of the week swiping to the right, and going to the specific day too choosing it from this screen too.

On the other hand, if you swipe down it would be useful to see the course of the current day, and if you continue going down of the next days too. Something like this:

![eltiempo2](https://cloud.githubusercontent.com/assets/4170088/20340122/58eb2630-abe0-11e6-9ab2-956c2af141b6.jpg)

Another nice approach is the one from the yahoo weather app. In this case, it shows the general info of the day, the evolution of the current day in an horizontal bar, and finally a general picture of the week. In this way I would suggest something similar too, that swiping right you could see the difderent days of the week, and swiping down the hourly evolution of the current day.

![yahoo](https://cloud.githubusercontent.com/assets/4170088/20340369/80650162-abe1-11e6-966f-28e31294cb3f.png)

**Comment by Yonjuni** [comment]
The redesign will include a forecast similar to the suggestion from @logos88 
1. course of the day can be scrolled horizontally (data every three hours according to the API)
2. weekly forecast (5 days according to the API) will be a listview 
3. The entire data from a city will be a list with the following items: overview, details, day, week and sun the list can be scrolled up- and downwards.

**Comment by Yonjuni** [comment]
Closed #20
