### ISSUE TITLE
API key - One Call 3.0

### ISSUE THREAD

**Issue by eggercomputerchaos** [SecUSo/privacy-friendly-weather#201]
Hi, 
just installed the App 3.1.1 and created an API key on https://home.openweathermap.org

If I try to use the url given in the app:
`https://api.openweathermap.org/data/2.5/onecall?lat=<lat>&lon=<lon>&units=metric&appid=<API key>`
 the response is:
`message	"Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."`

I ask the support and they answered:
`One Call 1.0 (2.5) is deprecated for all new and free users. We recommend everyone to use our new One Call 3.0, an updated version.`

Is there a way to add the One Call 3.0 in the app?
It would be nice 
Thanks

**Comment by woheller69** [comment]
my latest version of RadarWeather supports OneCall API 3.0
https://f-droid.org/de/packages/org.woheller69.weather/

**Comment by eggercomputerchaos** [comment]
I allready found RadarWeather and OneCall API 3.0 works 
Thanks
unfortunately the weather data seems to be not very accurate for west europe
weather forecast says clouds the whole time but here is most sunny

**Comment by woheller69** [comment]
OpenWeather is quite conservative.
At least it is rarely worse than predicted

**Comment by eggercomputerchaos** [comment]
:-) :-) :-)
