### ISSUE TITLE
Select a default location

### ISSUE THREAD

**Issue by subiol** [SecUSo/privacy-friendly-weather#21]
Allow the user to set a default location. This location would then be shown automatically when the app opens instead of the list of locations. This is a feature most weather apps have as it saves one click to the user.

It could also be used for the widget (https://github.com/SecUSo/privacy-friendly-weather/issues/18).

I do not have the GPS on by default so I do not use this following option, but another common feature is instead of the default location being a fixed location, have it set by the GPS, so it is always shows the weather of the present location.

**Comment by Yonjuni** [comment]
As it is a Privacy Friendly App (more info: secuso.org/pfa) the use of the location permission is not desired.

**Comment by Yonjuni** [comment]
In the redesign the list of locations will be moved to the menu in the app, thus, opening the app will show a default location (the first location of the list)

**Comment by Yonjuni** [comment]
Closed #21
