### ISSUE TITLE
Crash on Android 4.3.1

### ISSUE THREAD

**Issue by AlfaOmega33** [SecUSo/privacy-friendly-weather#22]
Hi! The app crash always; Is possible add a support for Android 4.3.1. and for the corresponding version of CyanogenMod and Replicant OS??

**Comment by Yonjuni** [comment]
At this moment we unfortunately cannot support version lower than Android 5.0 (SDK 21). But there might be support in the future.

See: https://github.com/SecUSo/privacy-friendly-weather/issues/19

**Comment by Yonjuni** [comment]
Hey, we just found a possibility to downgrade to app to your version. This will be added with one of the next updates.

**Comment by AlfaOmega33** [comment]
Ok, thank you!
