### ISSUE TITLE
This location is not already in the list

### ISSUE THREAD

**Issue by Primokorn** [SecUSo/privacy-friendly-weather#23]
Hi,
I already put the city 'Annecy' as a permanent location bu I can't select it from the main screen.
If I try to add it again, I have the following message: 'This location is already in the list'. As you can see in the screenshot below, 'Annecy' is not here.

Thanks.

![fmhgfmfz](https://cloud.githubusercontent.com/assets/5938828/20261300/7acb9e76-aa5d-11e6-96d7-e5870b664234.png)

**Comment by Yonjuni** [comment]
Thanks for the comment. Have you tried to re-install the application? Please, let me know if you still experience the same problem after re-install.

**Comment by Primokorn** [comment]
No changes.

**Comment by Yonjuni** [comment]
Have you changed the order of the cities by drap and drop?

**Comment by Primokorn** [comment]
Nope. I have only added a new city.

**Comment by Yonjuni** [comment]
I have found the problem and it will be solved in the redesign.

**Comment by Yonjuni** [comment]
Closed #23
