### ISSUE TITLE
italian app translation

### ISSUE THREAD

**Issue by xdema** [SecUSo/privacy-friendly-weather#24]
i made a translated menu, [strings](https://github.com/SecUSo/privacy-friendly-weather/pull/9/commits/a633b988c9885e388d5675d8e23eb7338449b197)  and [array](https://github.com/SecUSo/privacy-friendly-weather/pull/8/commits/0e5fbf2ca7b78c8b4bfc5fe733cea28bcef3b217)  commit.
Please, may you add the italian language on your app?

**Comment by Yonjuni** [comment]
Thanks, we have already seen it. We currently have an Italian speaker who talks a look at the translation, then it will be added for the next version.

**Comment by Yonjuni** [comment]
Closed #24
