### ISSUE TITLE
Use of weather icons

### ISSUE THREAD

**Issue by logos88** [SecUSo/privacy-friendly-weather#25]
Using icons instead of words would help to watch the weather much faster with only a glance. For example, instead of "clouds" it would appear an image of clouds. The same for a sundy or raining day. And even for words like wind speed or time sunrise or sunset which can be easily be substituted with their correspondent images.

This way it needs less space too so you can put more info in just a row : )

**Comment by Yonjuni** [comment]
The redesign will include icons at the following locations:
- weekly forecast
- course of day
- sunset/sunrise

**Comment by Yonjuni** [comment]
Closed #25
