### ISSUE TITLE
add changelog to fdroid

### ISSUE THREAD

**Issue by treakiandroid** [SecUSo/privacy-friendly-weather#32]
hi,

please add a link to change log to the fdroid repository. thanks

**Comment by Yonjuni** [comment]
Here is the changelog: https://github.com/SecUSo/privacy-friendly-weather/blob/master/CHANGELOG.md

Were should I add it to?

**Comment by sciamano** [comment]
looks like you have to add it to meta-data, see e.g. [here](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.stoutner.privacybrowser.standard.txt)
they have a field
`Changelog:https://www.stoutner.com/privacy-browser/changelog/`
and you don't

**Comment by Yonjuni** [comment]
Thanks, I just added it
https://gitlab.com/fdroid/fdroiddata/merge_requests/1859
