### ISSUE TITLE
feature request: cyanogenmodweatherprovider

### ISSUE THREAD

**Issue by treakiandroid** [SecUSo/privacy-friendly-weather#33]
hi,

it would be grate if you could implement the interface used do serve as cyanogenmodweatherprovider. Right niw i have in my system settings (CM13) the weather option in which is only written that i need to install a weather provider. when i tap that link its forwards to an froid search without any result's (probably on google play could be found some but i am using my device completely without).

so it would be grate if you could implement that.

thanks

**Comment by treakiandroid** [comment]
oops, lookes like ive done a duplicate to #28

**Comment by Yonjuni** [comment]
No Problem ;)
