### ISSUE TITLE
bug: to low contrast on some icons

### ISSUE THREAD

**Issue by treakiandroid** [SecUSo/privacy-friendly-weather#35]
![screenshot_20161127-050159](https://cloud.githubusercontent.com/assets/7935237/20645442/e21b3c3e-b45e-11e6-8fd2-85f7b0ac86b2.png)

see this screenshot, the icon of Berlin is mostly invisible do to muchto low contrast/thin line. maybe you could find something better there

also it is called Lüneburg and not Luneburg. I was also unable to find it inder its correct name. so add an umlaut-disable-conversiin search parallel by searching after the real name.

thanks

**Comment by paulle** [comment]
I would like too to see 'higher contrast icons', because it makes it easier for eyes and easier grabbing the weather information at quick glance.

**Comment by Yonjuni** [comment]
Either the icon contrast or the background colour will be changed.

**Comment by Yonjuni** [comment]
Closed #35
