### ISSUE TITLE
Times are GMT, not current city's

### ISSUE THREAD

**Issue by throwaway42** [SecUSo/privacy-friendly-weather#36]
Viewing forecast for a city doesn't show local time but GMT. This is confusing and leads to wrong information.
This already had caused trouble a few times for me when the app readings lead me not to bring a coat for the night when in reality I was reading the afternoon temperature. I froze my ass to death and that's how I discovered this bug.

**Comment by Yonjuni** [comment]
The local time of the city will be displayed with the according time zone. 
E.g. Darmstadt 14:30 (MEZ)

**Comment by Yonjuni** [comment]
Closed #36
