### ISSUE TITLE
missing dropdown-menu

### ISSUE THREAD

**Issue by paulle** [SecUSo/privacy-friendly-weather#42]
I nver found or saw the dropdown-menu mentioned in the popup.
Don't know if I'm too stupid to find it or it isn't.    (see screenshot)
![screenshot_20170129-121544](https://cloud.githubusercontent.com/assets/4852079/22405938/147021dc-e64a-11e6-857b-71bb7d53ff0c.png)

**Comment by Yonjuni** [comment]
Thanks for reporting, however I will close this issue, as it will vanish with version 2.0 that will be published soon.
