### ISSUE TITLE
Missing locations

### ISSUE THREAD

**Issue by stegmannt** [SecUSo/privacy-friendly-weather#45]
Hi,

while playing around with the app I noticed that there are some missing locations. E.g. the app finds "Darmstadt, DE" or "Wolkenstein, DE", both of which are cities, but not "Mömlingen, DE" (the village), which can be found via OpenWeatherMap directly or other apps using OWM.

As I unterstand Privacy Friendly Weather uses http://openweathermap.org/help/city_list.txt as lookup table for city ids, which seems to show cities only. 

There is another list mentioned in the API documentation, which also shows smaller villages http://bulk.openweathermap.org/sample/city.list.json.gz

It would be great, if you could consider switching to the json list, or alternativley, allow to add city IDs directly instead of searching in the lookup table.

Thanks!

**Comment by kolewu** [comment]
The CSV list is no longer available and the one included in the sources is either outdated or too small. I have made a simple python `owm-cities.py` script that uses the data from http://bulk.openweathermap.org/sample/city.list.json.gz to create a CSV list (just redirect the output to a file).
```python
#!/usr/bin/python3
"""Create CSV cities list from OpenWeathermap json list.

Usage: owm-cities.py ?filename?

If the default filename exists, it is used. The default can be
overwritten by a commandline argument. If the given or default file
doesn't exist, the download URL is used.

"""

import sys
import os.path
import urllib.request
import gzip
import json

filename = 'city.list.json.gz'
url = "http://bulk.openweathermap.org/sample/city.list.json.gz"
useFile = True

if len(sys.argv) > 1:
    filename = sys.argv[1]
if not os.path.exists(filename):
    useFile = False

if useFile:
    with open(filename, 'rb') as f:
        zdata = f.read()
else:
    with urllib.request.urlopen(url) as response:
        zdata = response.read()

data = gzip.decompress(zdata)
cities = json.loads(data)

for city in cities:
    print(f"{city['id']}\t{city['name']}\t{city['country']}\t-")
```
Unfortunately the json-list contains many combinations of name and country (and that's not different US states) with different IDs, don't know if this is a problem with the current code. The random samples outside the US I examined are the same entity with slightly differing coordinates, but the ones from the US were from different states. So maybe the ID should be displayed, too and it should be possible to choose a city by it's ID.

Additionally the json-list doesn't contain the postal codes.

**Comment by sleep-yearning** [comment]
The list is now updated from the most recent JSON. @stegmannt you can now also find Mömlingen and many more places.
Thank you for the script @kolewu, came in very handy with few changes!

**Comment by dexterousdex** [comment]
@sleep-yearning It's great that this issue has been closed, but there's still no new release including the fix.  What needs to happen to get a new certain tagged and made available on the play store?

**Comment by sleep-yearning** [comment]
A new release just went live 2 days ago, it might take some more days to appear in the playstore though.
Thanks for your patience!
