### ISSUE TITLE
UV index 

### ISSUE THREAD

**Issue by dimqua** [SecUSo/privacy-friendly-weather#46]
Please add UV index info to the app.

**Comment by Kamuno** [comment]
Openweathermap does not include this data via their API as far as I can see

**Comment by kolewu** [comment]
The API now contains the UV index: https://openweathermap.org/api/uvi But only for professional and enterprise accounts.

**Comment by woheller69** [comment]
One Call API contains this and it is free

**Comment by woheller69** [comment]
> The API now contains the UV index: https://openweathermap.org/api/uvi But only for professional and enterprise accounts.

It also works with my API key. Forecastie seems to use this API.

**Comment by woheller69** [comment]
I added UV to week forecast in my newmaster branch using OpenWeather One Call API

**Comment by sleep-yearning** [comment]
Is added into the app, closing.
