### ISSUE TITLE
http -> https ?

### ISSUE THREAD

**Issue by LibrEars** [SecUSo/privacy-friendly-weather#48]
When using [Net Monitor](https://f-droid.org/packages/org.secuso.privacyfriendlynetmonitor/) it shows an **unencrypted http** connection for privacy-freiandly-weather installed over f-droid.

Why not https for a privacy-friendly app (I'm not into app programming)?

**Comment by Yonjuni** [comment]
Unfortunately, we are limited to HTTP by the free API of OpenWeatherMap. If we would use HTTPS we would not be able to provide a free service. Here is the info from OpenWeatherMap: http://openweathermap.org/price

See related issues:
https://github.com/SecUSo/privacy-friendly-weather/issues/40
https://github.com/SecUSo/privacy-friendly-weather/issues/27

**Comment by LibrEars** [comment]
This is stupid. Why would anybody pay for a standard web technology. Maybe you should let the issue open because it is very fundamental and more people will ask...
Thank you anyway.

**Comment by Yonjuni** [comment]
We will leave it open.

**Comment by Yonjuni** [comment]
Done.
