### ISSUE TITLE
Add new distance units: Km/s

### ISSUE THREAD

**Issue by bmenant** [SecUSo/privacy-friendly-weather#57]
For now, one can choose between Miles and kilometers. But the wind speed is actually displayed in meters per second (m/s).

In my region (France), it is much more usual to give speeds in Kilometers per hour (km/h). 

I'd rename the settings option "Kilometer" to "Meters per seconds" and add a new option "Kilometers per seconds". And maybe rename accordingly "Miles" to "Miles per seconds"?

**Comment by sleep-yearning** [comment]
so far wished units: miles per hour, km/h, m/s. Anything missing?

**Comment by StyXman** [comment]
https://en.wikipedia.org/wiki/Speed#Units also mentions knots, feet/s and mach.

**Comment by kojid0** [comment]
> Anything missing?

Beaufort scale: https://en.wikipedia.org/wiki/Beaufort_scale
It's already available in RadarWeather, but km/h would be nice, indeed

**Comment by sleep-yearning** [comment]
This is resolved as of db0c23ea1fe680037bae835813a62dd4ae40b7f6.
I didn't include mach, since it did not seem relevant to me.
