### ISSUE TITLE
New release doesn't install on Android 5.0.2

### ISSUE THREAD

**Issue by surferjoeit** [SecUSo/privacy-friendly-weather#58]
Hello,
i tried to install latest release but i can't. I download apk file but cannot access it through file manager. When i open download folder it crashes. I had the same problem with other apps, it has been solved by updating build tools. It seems the same issue here.
See:

https://issuetracker.google.com/issues/64434571

Thanks!

**Comment by Kamuno** [comment]
Tested on Android 5.0. Can't reproduce on v2.2
