### ISSUE TITLE
Wind direction missing and speed mostly missing

### ISSUE THREAD

**Issue by mjray** [SecUSo/privacy-friendly-weather#59]
Wind speed and direction are fairly important. Wind speed only seems to be shown for the current details and wind direction doesn't seem to be shown anywhere. I'd prefer wind speed and a direction arrow instead of the humidity on the "week" panel and in addition on "details" and "course of the day".

Weather version 2.0 on Android 5.1.1 Lollipop tablet

(Version 2 is mostly a great improvement with a much easier overview and it seems to cache forecasts when offline, making it more useful on wifi-only devices.)

**Comment by woheller69** [comment]
![wind](https://user-images.githubusercontent.com/68678880/91007476-5c295580-e5dc-11ea-9b2b-5d1970151cd9.png)

**Comment by sleep-yearning** [comment]
Thanks @woheller69 for the realization!
