### ISSUE TITLE
Add "night icons"

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-weather#60]
The current version uses the same icons for day and night. Therefore, it's a bit confusing if the sun shines at night ;-) 
We should add "night icons" for this purpose, the API from OpenWeatherMap also supports this :-)

**Comment by M1Aston** [comment]
Are developers monitoring this website?

**Comment by petermayer** [comment]
@M1Aston Yes, absolutely. This is still on our list.

**Comment by sleep-yearning** [comment]
fixed with 204c949bd4ee7715e81a0d9f620226de4faf2c3b
thanks @woheller69
