### ISSUE TITLE
Weather (Privacy Friendly) App crash, when click multiple times on refresh button.

### ISSUE THREAD

**Issue by iamank1t** [SecUSo/privacy-friendly-weather#62]
#### Expected behavior
The app is showing me weather of my city on main screen and there is a refresh button on top right of app which refresh the weather details. Now if i click multiple times on the refresh button, then app needs to manage multiple clicks and update the weather with new information (if there is any new change in weather information).

#### Actual behavior
When i click on refresh button multiple times rapidly the app got crashed. Sometimes app got crash in 3-4 clicks or sometimes it take 6-8 clicks on refresh button. But it is crashing every time on clicking refresh button multiple times.

#### How to reproduce
To reproduce the bug follow the following steps :-
- Download app from play store.
- Enter your first location in app, now you have a screen which shows weather details of your location.
- Look at top right of app, you will see a refresh button. Now press refresh button rapidly 4 -5 times and the app got crashed. (For better understanding watch recording of bug)
- Sometimes app got crash in 3-4 clicks or sometimes it take 6-8 clicks on refresh button.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v2.0
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=0OQLi7lPLBE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/weather-privacy-friendly-app-crash-when-click-multiple-times-on-refresh-button">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Yonjuni** [comment]
Thanks for reporting this bug.
