### ISSUE TITLE
Loss of functionality in version 2

### ISSUE THREAD

**Issue by lfourquaux** [SecUSo/privacy-friendly-weather#63]
Some functionalities seem to have been lost in the UI redesign for version 2 (or maybe it's not discoverable enough):

- being able to display the "Course of the day" weather (by 3-hours slices) for other days of the week;

- being able to seen rainfall amounts;

- being able to reorder the list of locations without clearing and recreating the list.

The fist two were most useful and the app feels crippled without them.  Could you please add these back?

**Comment by M1Aston** [comment]
Yes, there should be more information for other days of the week, preferrably uncluding a quick view for highest and lowest temperatures.

**Comment by sleep-yearning** [comment]
those issues are resolved, except the re-sorting. Since there is a separate issue for that, I'm closing this.
