### ISSUE TITLE
Widget doesn't update correctly

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-weather#67]

**Comment by caugner** [comment]
For me, the widget with the 5-day forecast doesn't load at all after adding it to the homescreen. It just shows 42 degree and 42 percent humidity for all days.

**Comment by kolAflash** [comment]
Same here. Android-8.1 (LineageOS-15.1)

Looks like related:
https://github.com/SecUSo/privacy-friendly-weather/issues/68

**Comment by Janosch** [comment]
I have the same problem with the 5-day-widget. The other widgets seem to work (3-day, and single-day).

Is there still someone maintaining SecUSo apps? It appears that this project is dead.

**Comment by Kamuno** [comment]
The project is not dead at all.. We are actively working on all of the projects. But we have 35+ repositories for privacy friendly apps and just a very small team working on it. The apps are developed by computer science students and maintained by the SECUSO-Team.

We have to prioritize issues by importance and there is a constant stream of issues rolling in. I hope you understand.

**Comment by esrat** [comment]
> 
> 
> The project is not dead at all.. We are actively working on all of the projects. But we have 35+ repositories for privacy friendly apps and just a very small team working on it. The apps are developed by computer science students and maintained by the SECUSO-Team.
> 
> We have to prioritize issues by importance and there is a constant stream of issues rolling in. I hope you understand.

I do understand how difficult it is to maintain students' (one-time-)projects with only a small team. Maybe you can aquire some more additional contributors here to speed up developement?

I just want to comment that all common / preinstalled weather apps do contain ad- and spyware. Even the alternative of the (enforcedly) payed app-version of the "Deutscher Wetterdienst" is not optainable without a Google-Account.

In my eyes, these arguments should make this privacy-friendly-weather-app a **top priority**!
