### ISSUE TITLE
App does not update until I switch between views

### ISSUE THREAD

**Issue by xaverdh** [SecUSo/privacy-friendly-weather#68]
When I open the app, it is frozen in the state from the time it was closed until I switch between views. For example, opening the settings and switching back to the main view, unfreezes the app.

Im on lineage if that matters.

**Comment by fliegentoeter** [comment]
Same here on Lineage OS 14.1

**Comment by der-Daniel** [comment]
Same

**Comment by der-Daniel** [comment]
I have the same issue. I solve it by closing and reopening the app.
I guess it should be an easy fix, since it appears that the UI is just not updated programmatically.

**Comment by M1Aston** [comment]
Developers, are you reading this?

**Comment by der-Daniel** [comment]
@M1Aston https://github.com/martykan/forecastie is a nice alternative.

**Comment by kolAflash** [comment]
Same here. Android-8.1 (LineageOS-15.1)
