### ISSUE TITLE
Show highs and lows for 5-day forecast

### ISSUE THREAD

**Issue by earboxer** [SecUSo/privacy-friendly-weather#70]
It seems like the 5-day forecast is just showing the temperature at noon on each day.

It would be nice to see the highs and the lows, perhaps rendered like darksky.net does.

<img width="797" alt="screen shot 2018-05-18 at 11 08 23 am" src="https://user-images.githubusercontent.com/12452738/40242544-ed12fd6e-5a8b-11e8-85a9-a9231ae0e84e.png">

**Comment by M1Aston** [comment]
It would also be nice to get a better provider than openweathermaps, because the predictions sometimes (too frequently) are really bad.

**Comment by petermayer** [comment]
@M1Aston This seems to be separate from the forecast. If you are interested in additional weather providers, please see #28.

**Comment by sleep-yearning** [comment]
Highs and lows are implemented now. Not as fancy but for now sufficient I think.
