### ISSUE TITLE
Extremely wrong forecast

### ISSUE THREAD

**Issue by bege10** [SecUSo/privacy-friendly-weather#73]
That's a pity: I use it for a week now and the temperatures for several cities in Germany are up to 5 degrees too low and where there is full sunshine it shows clouds. I guess that's something the app cannot change but makes it useless.

**Comment by petermayer** [comment]
Sorry to hear that, but the app fully relies on the data provided by openweathermap. Therefore, as you rightly assume, we have no influence on the correctness or precision of the data.
