### ISSUE TITLE
Size of the widget

### ISSUE THREAD

**Issue by fliegentoeter** [SecUSo/privacy-friendly-weather#75]
Is there a way to change the size of the widget? I can only choose 1x4 and it does not look good on my homescreen :)
Need something like 1x5 for it to fit correctly.

![screenshot_20180804-111426](https://user-images.githubusercontent.com/8972985/43674813-526dd9ec-97d9-11e8-8401-ce364f29e7bf.png)

**Comment by caugner** [comment]
Usually you can resize it by long pressing the widget. At least this works for me using the Nova Launcher.

However, the widget is not looking very good at 2x1, for instance.

**Comment by Kamuno** [comment]
There are only 2 widgets and you should be able to resize them.
