### ISSUE TITLE
looks too simple

### ISSUE THREAD

**Issue by M1Aston** [SecUSo/privacy-friendly-weather#76]
I'm sorry to say I find the overall looks of the app somewhat simplistic\amateurish. Information is scattered over five different, large blue zones\blocks, some of which contain only a single item of information.
1. current   2. details   3. course of the day   4. week   5. sun (this block 5 is almost nothing but empty space)

There could easily only be three blocks, providing a cleaner look, by combining block 1, 2 and 5. Suggestion:
1. current, details, sun
2. course of the day
3. week

**Comment by esrat** [comment]
The distribution of contents over the existing containers is surely open to discussion but I won't change the overall look-and-feel.
There is no need for another tool with complicated UI and expensive animations when you just want to look at some weather forecasts! The more important question should be how to integrate new elements like the lowest temperatures I proposed in #86.
At least at my device there should be enough free space within the week-container to add these directly without having to scroll horizontally.

**Comment by petermayer** [comment]
We believe the look-and-feel of the app is highly subjective and we have currently no plans to change it.
