### ISSUE TITLE
Widget with intraday (three-hourly) forecast

### ISSUE THREAD

**Issue by PhilippWendler** [SecUSo/privacy-friendly-weather#80]
It would be great to have a widget that shows the forecast for the current day. Such an overview is very helpful when leaving home in the morning, because a daily summary is often too coarse for deciding what to wear. The layout could be just like the existing four-day forecast widget, just with the data from the intraday forecast that the app already shows.

**Comment by sleep-yearning** [comment]
I recently added an intra-day widget. I hope it's useful. :)

**Comment by PhilippWendler** [comment]
Nice, thanks!
