### ISSUE TITLE
Add an option to display times in local timezones

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-weather#81]

**Comment by byronmansfield** [comment]
I came on here looking to report what I thought was a bug, but I think this might be related to what I'm seeing. The time at the top by the location name is different than my local time. Is there a way to adjust this? Or is this a bug? Or is this simply the feature enhancement called out in this issue?

**Comment by Kamuno** [comment]
Timezones are now part of the API
https://openweathermap.org/current#geo
