### ISSUE TITLE
Lowest temperatures in the four-day-forecast

### ISSUE THREAD

**Issue by esrat** [SecUSo/privacy-friendly-weather#86]
Hi,
I don't know any details of the used weather API so I don't know if this is possible in a simple manner.
But it does look at least "strange" that I can see the highest temperature for every day of the four-day-forecast but not the lowest ones!?
These are most important when e.g. looking at the freezing temperature (in traffic and other domains).

So could you please add the lowest temperature as well?

(#63 did already mention this but is mainly about other things.)

**Comment by Kamuno** [comment]
The API does include this data. This would be possible

**Comment by esrat** [comment]
Is it also achievable for one of the next versions?

To ask a heretical question: Are there any new releases planned yet?
After the last little changes which would make the app usable together with a firewall, I expected a new release. But there was none.

**Comment by sleep-yearning** [comment]
There will probably be a new release soon.
The app is currently being worked on.

**Comment by sleep-yearning** [comment]
Highest & lowest temperatures are implemented throughout the app (including widgets). The highest temperature is much more reliable as well. Hence I'm closing this. Regarding a new release, there will probably be one later this year.
