### ISSUE TITLE
Update weather tabs after city list changes

### ISSUE THREAD

**Issue by esrat** [SecUSo/privacy-friendly-weather#89]
Right now, you have to restart the app if there is any change of the city list (add any additional city or delete one by wiping it out of the list).
I consider that a bug.

**Comment by sleep-yearning** [comment]
Thank you for your report. In our experience, the list was updated when switching between activities too. Is this the case for you too or can you only achieve an updated list by restarting the app? 
It is of course a bug, however we might not prioritize it soon because of more impactful ones.

**Comment by esrat** [comment]
Yes, first I tried back and forth, opening an closing the city management, switching to other apps and back but I got no update. --- But then I realised when opening and closing the settings, the line of city tabs got updated without having to restart the app!
