### ISSUE TITLE
Make the city list re-sortable

### ISSUE THREAD

**Issue by esrat** [SecUSo/privacy-friendly-weather#90]
When the city list has more than two or three entries, the tab list for the weather panes quickly gets filled up. Most users would sort their cities by priority. Lower prioritised entries would be moved to the end.
But that is not possible right now. The list is quite static.

A personal example: I accidentally deleted an entry next to the start of my list (because I did not now that horizontally swiping would delete an entry without any confirmation). So I had to add it back in. But now, this most important city was sitting there at the end. So I had to delete and re-add every single entry of the list to sort the list the same way it was sorted before!

I have no Android developing experience but I would expect there should be some ready-made GUI component which realises re-sortable text lines.

**Comment by sleep-yearning** [comment]
solved as of 1254e05ce8e4d8ec1280237b8ed67b4338009998
