### ISSUE TITLE
App is not responding for pretty long time being opened

### ISSUE THREAD

**Issue by vadiof** [SecUSo/privacy-friendly-weather#91]
When I open the app it freezes for a long time (~10 sec). This happens not every time but only when I didn't open it for a long period. I have 17 locations in my list and it looks like the freezing caused by forecast updating

**Comment by woheller69** [comment]
Should be a lot better with the modified update policy:

https://github.com/woheller69/privacy-friendly-weather/commit/46b7fca5322007a3189b6e86e4eb917d97332aa1

But still the app starts quite slow when it has been killed before. It already takes quite a while before the app starts refreshing the data.

**Comment by woheller69** [comment]
Any ideas what makes startup and switching between activities so slow? With the changed update policy (only update the data of the current tab and not always update all) it is much better and more reactive but still very slow.
From starting the intent for ForecastCityActivity in SplashActivity until OnResume in ForecastCityActivity is reached it takes 5s on my (slow) Moto G3... Also switching from Manage Locations to ForecastCityActivity takes an eternity. It always goes through OnCreate and not directly to OnResume.

**Comment by vadiof** [comment]
It looks like fixed in 2.4
