### ISSUE TITLE
Certificate Authority of https://openweathermap.org/ is not trusted on older devices

### ISSUE THREAD

**Issue by dwi336** [SecUSo/privacy-friendly-weather#94]
Volley give a

com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

error, when trying to communicate with api.openweathermap.org on older devices. That's because the issuing CA (Sectigo.com) is not trusted in these devices. This results in an error updating the forecast and the citylist:

![Screenshot_2020-06-21-14-08-45](https://user-images.githubusercontent.com/30302193/85224763-debf4a00-b3cc-11ea-93ae-7393c5df0350.png)
![Screenshot_2020-06-21-14-08-48](https://user-images.githubusercontent.com/30302193/85224766-e121a400-b3cc-11ea-81c2-59b3a0bbad3d.png)

Google recommends in that cases

https://developer.android.com/training/articles/security-ssl#java

to load the corresponding crt-File of the CA and trust the CA for the app. In case of Sectigo the crt file can be found under

http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt

The crt file could be put in the app's asset folder and the VolleyHttpRequest class could be extended to trust the delived crt file. I have put the necessary changes in the following patch:

[VolleyHTTPRequest.patch.zip](https://github.com/SecUSo/privacy-friendly-weather/files/4809460/VolleyHTTPRequest.patch.zip)

I would appreciate if you could adopt the changes.

Thank you.

dwi336

**Comment by sleep-yearning** [comment]
Thanks for the help!
